@startuml
'https://plantuml.com/class-diagram



entity ShoppingCart {
    - HashMap<int, Order> orderMap
    + void addOrder(Order order)
    + void removeOrder(Order order)
    + float getTotalPrice()
}

entity Order {
    - int id
    - int userId
    - Timestamp created
    - isPaid boolean
    - HashMap<int, OrderItem> itemMap
    + void addItem(orderItem item)
    + void removeItem(orderItem item)
    + void updateItem(orderItem item)
    + float getTotalPrice()
}

entity OrderItem {
    - int id
    - int orderId
    - int quantity
    - Top top
    - Bottom bottom
    + Top getTop()
    + Bottom getBottom()
    + float getTotalPrice()
}

entity Top {
    - int id
    - String name
    - float price
    + String getName()
    + float getPrice()
}

entity Bottom {
    - int id
    - String name
    - float price
    + String getName()
    + float getPrice()
}

ShoppingCart .. Order
Order .. OrderItem
OrderItem .. Top
OrderItem .. Bottom
@enduml