@startuml
'https://plantuml.com/class-diagram


UserFacade --> UserMapper

class UserFacade {
    static User login(String email, String password)
    static User createUser(String email, String password, String role)
}

class UserMapper {
    static User login(String email, String password, ConnectionPool connectionPool)
    static User createUser(String email, String password, String role, ConnectionPool connectionPool)
}

class Order {

}


@enduml